/**
 * Generated by `tools/build-audio.mjs`. Do not edit by hand.
 *
 * How many recorded variations each sound id has under
 * `public/assets/sounds/<id>/`, and which music and ambience files exist.
 */
export const SAMPLE_COUNTS: Record<string, number> = {};

export const MUSIC_FILES: Record<string, string[]> = {};

export const AMBIENCE_FILES: Record<string, string[]> = {};
