/**
 * Generated by tools/build-audio.mjs. Do not edit by hand.
 *
 * SAMPLE_COUNTS: variations per sound id (sounds/<id>/01.ogg ...).
 * MUSIC_FILES / AMBIENCE_FILES: the files of each track and bed, relative to public/assets/.
 */

export const SAMPLE_COUNTS: Record<string, number> = {
  "amb.anvil": 4,
  "amb.bird": 6,
  "amb.buzz": 5,
  "amb.chain": 3,
  "amb.crackle": 2,
  "amb.creak": 6,
  "amb.crow": 2,
  "amb.drip": 5,
  "amb.gust": 3,
  "amb.hiss": 3,
  "amb.howl": 2,
  "amb.lap": 5,
  "amb.moan": 4,
  "amb.rumble": 2,
  "amb.shimmer": 3,
  "amb.squelch": 4,
  "amb.stones": 6,
  "amb.whisper": 4,
  "ambush": 3,
  "arrow.thunk": 4,
  "beam.arcane": 2,
  "beam.fire": 2,
  "beam.lightning": 2,
  "block": 6,
  "block.magic": 3,
  "boss.intro": 2,
  "boss.phase": 2,
  "boss.roar": 8,
  "boss.slam": 3,
  "boss.windup": 4,
  "buff": 3,
  "cast.arcane": 7,
  "cast.cold": 3,
  "cast.fire": 6,
  "cast.lightning": 4,
  "cast.physical": 3,
  "cast.poison": 5,
  "chest": 3,
  "combo": 2,
  "cone.cold": 2,
  "cone.fire": 2,
  "cone.poison": 3,
  "craft.success": 2,
  "crit": 3,
  "death.heavy": 2,
  "death.normal": 3,
  "debuff": 3,
  "door": 3,
  "drop.magic": 3,
  "drop.rare": 2,
  "drop.set": 2,
  "drop.unique": 2,
  "footstep.dirt": 6,
  "footstep.grass": 5,
  "footstep.metal": 4,
  "footstep.mud": 6,
  "footstep.sand": 5,
  "footstep.snow": 5,
  "footstep.stone": 5,
  "footstep.water": 5,
  "footstep.wood": 5,
  "gold": 5,
  "gold.land": 4,
  "gold.spill": 3,
  "heartbeat": 1,
  "hit.axe": 3,
  "hit.blunt": 4,
  "hit.bone": 4,
  "hit.chitin": 4,
  "hit.fist": 4,
  "hit.flesh": 4,
  "hit.heavy": 3,
  "hit.melee": 5,
  "hit.metal": 5,
  "hit.ooze": 5,
  "hit.pierce": 3,
  "hit.stone": 4,
  "hit.sword": 4,
  "hit.wood": 4,
  "howl": 3,
  "impact.arcane": 4,
  "impact.cold": 5,
  "impact.fire": 4,
  "impact.lightning": 4,
  "impact.poison": 5,
  "jump": 3,
  "kill.confirm": 3,
  "kill.elite": 2,
  "kill.multi": 2,
  "land": 2,
  "levelup": 2,
  "loot.clink": 6,
  "loot.grab": 3,
  "loot.legendary": 2,
  "loot.toss": 2,
  "monster.aberration.aggro": 4,
  "monster.aberration.attack": 4,
  "monster.aberration.death": 3,
  "monster.aberration.hurt": 4,
  "monster.beast.aggro": 4,
  "monster.beast.attack": 5,
  "monster.beast.death": 4,
  "monster.beast.hurt": 5,
  "monster.construct.aggro": 3,
  "monster.construct.attack": 4,
  "monster.construct.death": 2,
  "monster.construct.hurt": 4,
  "monster.demon.aggro": 4,
  "monster.demon.attack": 4,
  "monster.demon.death": 3,
  "monster.demon.hurt": 4,
  "monster.elemental.aggro": 2,
  "monster.elemental.attack": 3,
  "monster.elemental.death": 2,
  "monster.elemental.hurt": 4,
  "monster.humanoid.aggro": 4,
  "monster.humanoid.attack": 4,
  "monster.humanoid.death": 4,
  "monster.humanoid.hurt": 5,
  "monster.insect.aggro": 4,
  "monster.insect.attack": 4,
  "monster.insect.death": 3,
  "monster.insect.hurt": 4,
  "monster.ooze.aggro": 3,
  "monster.ooze.attack": 4,
  "monster.ooze.death": 2,
  "monster.ooze.hurt": 5,
  "monster.plant.aggro": 4,
  "monster.plant.attack": 4,
  "monster.plant.death": 2,
  "monster.plant.hurt": 4,
  "monster.swing": 4,
  "monster.undead.aggro": 4,
  "monster.undead.attack": 4,
  "monster.undead.death": 4,
  "monster.undead.hurt": 4,
  "nova.arcane": 4,
  "nova.cold": 3,
  "nova.fire": 3,
  "nova.lightning": 2,
  "nova.physical": 2,
  "nova.poison": 3,
  "parry": 6,
  "pickup.kind.armor": 4,
  "pickup.kind.gem": 3,
  "pickup.kind.jewel": 3,
  "pickup.kind.material": 5,
  "pickup.kind.potion": 3,
  "pickup.kind.weapon": 5,
  "pickup.magic": 2,
  "pickup.rare": 2,
  "player.death": 4,
  "player.evade": 2,
  "player.hurt": 5,
  "player.hurtHeavy": 4,
  "player.stunned": 1,
  "portal": 3,
  "potion": 3,
  "quest.complete": 2,
  "roar": 4,
  "screech": 3,
  "shoot.physical": 3,
  "shrine": 2,
  "skillpoint": 2,
  "slam": 4,
  "spell.chainLightning": 3,
  "spell.curse": 3,
  "spell.explosion": 5,
  "spell.heal": 4,
  "spell.meteor": 2,
  "spell.shield": 3,
  "spell.summon": 3,
  "spell.teleportIn": 3,
  "spell.teleportOut": 3,
  "spell.thunder": 3,
  "spell.volley": 2,
  "spell.whirlwind": 2,
  "stairs": 2,
  "swing.axe": 4,
  "swing.blade": 6,
  "swing.blunt": 3,
  "swing.fist": 3,
  "swing.heavy": 4,
  "swing.light": 3,
  "swing.pierce": 3,
  "telegraph": 3,
  "telegraph.long": 2,
  "ui.buy": 3,
  "ui.click": 4,
  "ui.close": 3,
  "ui.equip": 4,
  "ui.error": 3,
  "ui.hover": 3,
  "ui.open": 3,
  "ui.select": 3,
  "ui.sell": 3,
  "ui.tab": 3,
  "ui.unequip": 3,
  "wail": 4,
  "warcry": 3,
  "waypoint": 2
};

export const MUSIC_FILES: Record<string, string[]> = {
  "boss.dread": [
    "music/boss.dread/01.ogg"
  ],
  "boss.epic": [
    "music/boss.epic/01.ogg"
  ],
  "boss.metal": [
    "music/boss.metal/01.ogg"
  ],
  "boss.war": [
    "music/boss.war/01.ogg"
  ],
  "caverns": [
    "music/caverns/01.ogg"
  ],
  "crypt": [
    "music/crypt/01.ogg"
  ],
  "death": [
    "music/death/01.ogg"
  ],
  "desert": [
    "music/desert/01.ogg"
  ],
  "forest": [
    "music/forest/01.ogg",
    "music/forest/02.ogg"
  ],
  "foundry": [
    "music/foundry/01.ogg"
  ],
  "frozen": [
    "music/frozen/01.ogg",
    "music/frozen/02.ogg"
  ],
  "hell": [
    "music/hell/01.ogg"
  ],
  "hive": [
    "music/hive/01.ogg"
  ],
  "menu": [
    "music/menu/01.ogg"
  ],
  "swamp": [
    "music/swamp/01.ogg"
  ],
  "temple": [
    "music/temple/01.ogg",
    "music/temple/02.ogg"
  ],
  "tomb": [
    "music/tomb/01.ogg"
  ],
  "town": [
    "music/town/01.ogg",
    "music/town/02.ogg"
  ],
  "victory": [
    "music/victory/01.ogg"
  ],
  "void": [
    "music/void/01.ogg"
  ]
};

export const AMBIENCE_FILES: Record<string, string[]> = {
  "cave": [
    "sounds/beds/cave/01.ogg"
  ],
  "dungeon": [
    "sounds/beds/dungeon/01.ogg"
  ],
  "fire": [
    "sounds/beds/fire/01.ogg"
  ],
  "forest": [
    "sounds/beds/forest/01.ogg",
    "sounds/beds/forest/02.ogg"
  ],
  "hive": [
    "sounds/beds/hive/01.ogg"
  ],
  "machine": [
    "sounds/beds/machine/01.ogg",
    "sounds/beds/machine/02.ogg"
  ],
  "rumble": [
    "sounds/beds/rumble/01.ogg"
  ],
  "swamp": [
    "sounds/beds/swamp/01.ogg",
    "sounds/beds/swamp/02.ogg"
  ],
  "void": [
    "sounds/beds/void/01.ogg",
    "sounds/beds/void/02.ogg"
  ],
  "water": [
    "sounds/beds/water/01.ogg",
    "sounds/beds/water/02.ogg"
  ],
  "wind": [
    "sounds/beds/wind/01.ogg",
    "sounds/beds/wind/02.ogg"
  ],
  "wind.desert": [
    "sounds/beds/wind.desert/01.ogg",
    "sounds/beds/wind.desert/02.ogg"
  ],
  "wind.soft": [
    "sounds/beds/wind.soft/01.ogg",
    "sounds/beds/wind.soft/02.ogg"
  ]
};
