/**
 * Where every recorded sound comes from. All CC0 (each OpenGameArt entry's
 * licence box was checked by hand and lists CC0).
 *
 * `dir` is relative to the download root (default /tmp/slay-downloads/audio).
 * `fetch` lists what `build-audio.mjs --fetch` downloads; zips are unpacked
 * into `<dir>/<zip name>/`, plain files land in `<dir>/`.
 */

const OGA = 'https://opengameart.org/sites/default/files/';
const oga = (slug, author, files, dirName = slug) => ({
  page: `https://opengameart.org/content/${slug}`,
  author,
  dir: `oga/${dirName}/x`,
  fetch: files.map((f) => OGA + f),
});
const kenney = (slug, zip, dir) => ({
  page: `https://kenney.nl/assets/${slug}`,
  author: 'Kenney',
  dir: `kenney/${dir}/Audio`,
  fetch: [zip],
  kenney: dir,
});

export const PACKS = {
  // --- Kenney -----------------------------------------------------------------
  kr: kenney('rpg-audio', 'https://kenney.nl/media/pages/assets/rpg-audio/8e99002d76-1677590336/kenney_rpg-audio.zip', 'rpg'),
  ki: kenney('impact-sounds', 'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip', 'impact'),
  kf: kenney('interface-sounds', 'https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip', 'iface'),
  ku: kenney('ui-audio', 'https://kenney.nl/media/pages/assets/ui-audio/490d233f68-1677590494/kenney_ui-audio.zip', 'ui'),
  kj: kenney('music-jingles', 'https://kenney.nl/media/pages/assets/music-jingles/f37e530b9e-1677590399/kenney_music-jingles.zip', 'jingles'),

  // --- OpenGameArt: effects -----------------------------------------------------
  rsp: oga('rpg-sound-pack', 'artisticdude', ['rpg_sound_pack.zip']),
  r80: oga('80-cc0-rpg-sfx', 'rubberduck', ['80-CC0-RPG-SFX_0.zip']),
  swish: oga('swishes-sound-pack', 'artisticdude', ['swishes.zip']),
  melee3: oga('3-melee-sounds', 'remaxim', ['melee%20sounds.zip']),
  battle: oga('battle-sound-effects', 'Ogrebane', ['battle_sound_effects_0.zip']),
  zomb: oga('zombies-sound-pack', 'artisticdude', ['zombies.zip']),
  dungamb: oga('loopable-dungeon-ambience', 'JaggedStone', ['dungeon_ambient_1.ogg']),
  c100: oga('100-cc0-sfx', 'rubberduck', ['100-CC0-SFX_0.zip']),
  c100b: oga('100-cc0-sfx-2', 'rubberduck', ['sfx_100_v2.zip']),
  moan: oga('ghost-monster-voice-moaning-growling', 'qubodup', ['qubodup-GhostMoans.zip']),
  swamp: oga('swamp-environment-audio', 'LokiF', ['swamp.ogg']),
  heart: oga('heartbeat-sounds', 'bart', ['heartbeat_slow_0.wav', 'heartbeat_fast_0.wav']),
  creat: oga('80-cc0-creature-sfx', 'rubberduck', ['80-CC0-creature-SFX_0.zip']),
  creat2: oga('80-cc0-creture-sfx-2', 'rubberduck', ['80-CC0-creature-sfx-2.zip']),
  water: oga('40-cc0-water-splash-slime-sfx', 'rubberduck', ['water-splash-slime-sfx.zip']),
  freeze: oga('freeze-spell-0', 'artisticdude', ['freeze.wav']),
  magic: oga('magic-spell-sfx', 'JaggedStone', ['magical_1.ogg', 'magical_2.ogg', 'magical_3.ogg', 'magical_4.ogg', 'magical_5.ogg', 'magical_6.ogg', 'magical_7.ogg']),
  steps: oga('footsteps-leather-cloth-armor', 'HaelDB', ['footsteps.zip']),
  bfh: oga('75-cc0-breaking-falling-hit-sfx', 'rubberduck', ['sfx_breaking_and_falling.zip']),
  birds: oga('ambient-bird-sounds', 'isaiah658', ['birds-isaiah658.ogg']),
  hearth: oga('fireplace-sound-loop', 'PagDev', ['fire.wav']),
  tiny: oga('fantasy-sound-effects-tinysized-sfx', 'Vehicle', ['tinysized.zip']),
  loops30: oga('30-cc0-sfx-loops', 'rubberduck', ['sfx_loops.zip']),
  bang: oga('25-cc0-bang-firework-sfx', 'rubberduck', ['25-CC0-bang-sfx.zip']),
  gob: oga('goblins-sound-pack', 'artisticdude', ['goblins_0.zip']),
  fball: oga('fireball-1', 'diligentcircle', ['105016__julien-matthey__jm-fx-fireball-01.wav']),
  sword20: oga('20-sword-sound-effects-attacks-and-clashes', 'StarNinjas', ['sword_-_starninjas_1.zip', 'sword_clash_-_starninjas_0.zip']),
  crick: oga('crickets-ambient-noise-loopable', 'Wolfgang_', ['crickets_1.mp3']),
  wwoosh: oga('wind-whoosh-loop', 'SketchMan3', ['wind%20woosh%20loop.ogg']),
  tele: oga('teleport-spell', 'Ogrebane', ['teleport.wav']),
  mud: oga('25-cc0-mud-sfx', 'rubberduck', ['25-CC0-mud-sfx.zip']),
  troll: oga('big-scary-troll-sounds', 'Darsycho', ['troll-roars.ogg', 'troll-idle-noises.ogg']),
  crackle: oga('fire-crackling', 'AntumDeluge', ['fire-1.ogg']),
  hit5: oga('5-hit-sounds-dying', 'TinyWorlds', ['5Hit_Sounds.zip']),
  ice: oga('ice-spells', 'bart', ['icespells.zip']),
  spells: oga('spell-sounds', 'HaelDB', ['electricspell.ogg', 'electricspell2.ogg', 'healing.ogg', 'teleport.ogg']),
  acc: oga('fantasy-accessory-sfx-library', 'Vehicle', ['accessory.zip']),
  wpn: oga('fantasy-weapons-and-apparel-sfx-library', 'Vehicle', ['weapons-apparel.zip']),
  shield: oga('10-impactshield-blocks', 'StarNinjas', ['impact_-_starninjas.zip']),
  sack: oga('sack-of-gold', 'Amarikah', ['gold_sack.wav']),
  snarl: oga('monster-snarls', 'Darsycho', ['monster-snarl-5.ogg', 'monster-snarl-attack.ogg', 'monster-snarls-2.ogg', 'monster-snarls.ogg', 'monsters-snarls-3.ogg']),
  mino: oga('osare-minotaur-sounds', 'HaelDB', ['mino1.wav']),
  sdoor: oga('stone-door', 'bonebrah', ['stone_door.ogg']),
  dsteps: oga('different-steps-on-wood-stone-leaves-gravel-and-mud', 'TinyWorlds', ['%5Bkdd%5DDifferentSteps_0.zip']),
  drip: oga('dripping-water-loop', 'qubodup', ['atmosbasement.mp3_.flac']),
  wind1: oga('wind1', 'Luke.RUSTLTD', ['wind1.wav', 'wind2.wav', 'wind3.wav', 'wind4.wav', 'wind5.wav']),
  wind: oga('wind', 'IgnasD', ['wind.zip']),
  crow: oga('crow-caw', 'zeroisnotnull', ['crow_caw.wav']),
  yell: oga('male-gruntyelling-sounds', 'HaelDB', ['yelling%20sounds.zip']),
  hurt: oga('hurt-death-sound-effect-for-character', 'Badre-Eddine', ['death%20sound%20effect.zip']),
  done: oga('completion-sound', 'HaelDB', ['gmae.wav']),
  drain: oga('energy-drain', 'qubodup', ['qubodup-PowerDrain.ogg']),
  gbreath: oga('ghost-breath', 'qubodup', ['ghostbreath.flac']),
  ghost: oga('ghost', 'Ogrebane', ['ghost.wav']),
  flame: oga('catching-fire', 'themightyglider', ['flame.ogg']),
  clink: oga('metal-impact-sounds', 'BMacZero', ['bing1.wav', 'bong1.wav', 'clink1_0.wav', 'clink2.wav', 'clink3.wav', 'thud2.wav', 'thud3.wav']),
  elec: oga('electricity-game-sound-pack', 'faxcorp', ['charge.wav', 'chargestart.wav', 'crackleelectricityloop.wav', 'death_1.wav', 'deathboom.wav', 'groundhit.wav', 'hit.wav', 'powerdown.wav', 'powerup.wav', 'shieldhit.wav', 'snaploop.wav', 'teleport_1.wav']),
  buzz: oga('electric-buzz', 'themightyglider', ['buzz.ogg']),
  cure: oga('cure-magic', 'Someoneman', ['curemagic.zip']),
  earth: oga('earth-element-magic-spell', 'qubodup', ['Earth%20Element%20Magic%20Spell_3.ogg']),
  rsfx: oga('random-sfx', 'Écrivain', ['SFX.zip']),
  ignite: oga('flare-ignition', 'qubodup', ['ignition.flac']),
  boom: oga('explosion-0', 'TinyWorlds', ['explosion.wav']),
  farboom: oga('muffled-distant-explosion', 'NenadSimic', ['nenadsimic__muffled%20distant%20explosion.ogg']),
  scifi: oga('50-cc0-sci-fi-sfx', 'rubberduck', ['sci-fi-sfx.zip']),
  shatter: oga('ice-breakingshattering', 'IgnasD', ['IceShatters_0.zip']),
  whoosh: oga('air-whoosh', 'pyranostudios', ['whoosh2_0.wav']),
  portal4: oga('4-space-portal-sounds', 'Écrivain', ['tts.zip']),
  porta: oga('portal-sound', 'IgnasD', ['PortalSFX.zip']),
  thunder: oga('rain-long-thunder', 'WuxiaScrub', ['rain-thunder.ogg']),
  mw: oga('100-cc0-metal-and-wood-sfx', 'rubberduck', ['100-CC0-wood-metal-SFX.zip']),
  msfx1: oga('monster-sound-effects-pack', 'Ogrebane', ['monster_sfx_pack.zip']),
  msfx2: oga('monster-sound-effects-2', 'Ogrebane', ['monster_sfx_pack_2.zip']),
  msfx3: oga('monster-sound-pack-volume-1', 'Ogrebane', ['monster-sounds-volume-2.zip']),
  dark: oga('dark-ambiences', 'Ogrebane', ['dark_ambiences.zip']),
  laugh: oga('evil-laugh', 'AntumDeluge', ['laugh-evil-1.ogg']),

  // --- OpenGameArt: music ----------------------------------------------------------
  mMenu: oga('tragic-ambient-main-menu', 'HaelDB', ['ambientmain_0.ogg'], 'm-tragic-ambient'),
  mRuins: oga('town-in-ruins-loop', 'HaelDB', ['n3535n5n335n35nj.ogg'], 'm-town-ruins'),
  mInn: oga('medieval-the-old-tower-inn', 'RandomMind', ['The_Old_Tower_Inn.mp3'], 'm-old-tower-inn'),
  mDeath: oga('game-over-theme', 'CleytonKauffman', ['No%20Hope.mp3'], 'm-game-over'),
  mVictory: oga('victory', 'celestialghost8', ['Victory.mp3'], 'm-victory'),
  mEpic: oga('boss-battle-music', 'SubspaceAudio', ['Juhani%20Junkala%20-%20Epic%20Boss%20Battle%20%5BSeamlessly%20Looping%5D.wav'], 'm-boss-battle'),
  mGreat: oga('great-boss', 'Spring Spring', ['Great%20Boss.ogg'], 'm-great-boss'),
  mWar: oga('boss-battle-theme', 'CleytonKauffman', ['CleytonRX%20-%20Battle%20RPG%20Theme%20Var.ogg'], 'm-boss-theme'),
  mMetal: oga('boss-battle-2-symphonic-metal', 'nene', ['boss_battle_%232_metal_pack.zip'], 'm-boss-metal'),
  mTomb: oga('forgoten-tomb-ambience', 'kindland', ['Forgoten_tombs_1.mp3'], 'm-forgotten-tomb'),
  mCave: oga('cave-theme', 'HaelDB', ['cave%20themeb4.ogg'], 'm-cave-theme'),
  mCircle: oga('the-9th-circle', 'Joth', ['The%209th%20Circle%20V2.mp3'], 'm-9th-circle'),
  mShrine: oga('shrine', 'yd', ['shrine_0.ogg'], 'm-shrine'),
  mBreves: oga('breves-dies-hominis', 'ceninan', ['breves_dies_hominis.ogg'], 'm-breves'),
  mCreep: oga('creepy', 'TokyoGeisha', ['CrEEP.ogg'], 'm-creepy'),
  mIcy: oga('icy-realm-seven-and-eight', 'cynicmusic', ['019_seven_and_eight_7-8_combined.mp3'], 'm-icy-realm'),
  mWinter: oga('wintery-loop', 'Emma_MA', ['wintery%20loop.mp3'], 'm-wintery'),
  mCaravan: oga('desert-theme', 'yd', ['caravan.ogg.ogg'], 'm-desert'),
  mDungeon: oga('dungeon-ambience', 'yd', ['dungeon002.ogg'], 'm-dungeon'),
  mSirens: oga('sirens-in-darkness', 'cynicmusic', ['012_Sirens_in_Darkness.mp3'], 'm-sirens'),
  mForest: oga('creepy-forest-f', 'HaelDB', ['forest.ogg'], 'm-creepy-forest'),
  mDarkForest: oga('dark-forest-theme', 'cynicmusic', ['GameMusic_ForestTheme_24.mp3'], 'm-dark-forest'),
  mRats: oga('rat-sewer', 'HaelDB', ['ratsrats_0.ogg'], 'm-rat-sewer'),
  mProwler: oga('night-prowler', 'section31', ['S31-Night%20Prowler.ogg'], 'm-night-prowler'),
  mForestAmb: oga('forest-ambience', 'TinyWorlds', ['Forest_Ambience.mp3'], 'm-forest-ambience'),
  mIcyWind: oga('icy-heights', 'Écrivain', ['wind.ogg'], 'm-icy-heights'),
};
